# Generated by Django 5.2 on 2025-10-04 00:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userproductrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('agua', 'Agua'), ('jugo', 'Jugo'), ('gaseosa', 'Gaseosa'), ('alcohol', 'Alcohol')], default='agua', max_length=20),
        ),
    ]
