# Generated by Django 5.2 on 2025-05-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
