# Generated by Django 5.2 on 2025-05-15 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
